[ConnectorApi]
    # The port on which the Hub listens for subscriptions
    Port = "5000"

    # The type of the hub. Options: | common | custom:<your_hub_id> |
    # Used for custom implementations for subscriptions/events filtering
    # Defaults to: common
    HubType = "common"

    # The dispathing type. Options: | websocket | graphql | dispatch:* |
    # The driver can receive subscribe events and broadcast on one or more channels
    # Defaults to: websocket.
    DispatchType = "websocket"

    # Username is the username needed to authorize an observer to push data
    Username = ""

    # Password is the password needed to authorize an observer to push event data
    Password = ""
