[ConnectorApi]
    # The port on which the Hub listens for subscriptions
    Port = "5000"

    # The type of the hub. Options: | common | custom:<your_hub_id> |
    # Used for custom implementations for subscriptions/events filtering
    # Defaults to: common
    HubType = "common"

    # Username is the username needed to authorize an observer to push data
    Username = ""

    # Password is the password needed to authorize an observer to push event data
    Password = ""

    # CheckDuplicates signals if the events received from observers have been already pushed to clients
    # Requires a redis instance/cluster and should be used when multiple observers push from the same shard
    # Defaults to: false
    CheckDuplicates = false

[PubSub]
    # The url used to connect to a pubsub server
    # Note: not required for running in the notifier mode
    Url = "redis://localhost:6379/0"

    # The pubsub channel used for publishing/subscribing
    # Note: not required for running in the notifier mode
    Channel = "pub-sub"

    # The master name for failover client
    MasterName = "mymaster"

    # The sentinel url for failover client
    SentinelUrl = "sentinel:26379"

[RabbitMQ]
    # The url used to connect to a rabbitMQ server
    # Note: not required for running in the notifier mode
    Url = "amqp://guest:guest@localhost:5672"

    # The exchange name which holds all events
    # Expected type: fanout
    EventsExchange = "all_events"

    # The exchange name which holds revert events
    # Expected type: fanout
    RevertEventsExchange = "revert_events"

    # The exchange name which holds finalized block events
    # Expected type: fanout
    FinalizedEventsExchange = "finalized_events"
