name: Go Build

on:
  push:
    branches: [ main, rc/*, feat/* ]
  pull_request:
    branches: [ main, rc/*, feat/* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build
        run: make build
